### ISSUE TITLE
宣言の部分文字列で反応している…？

### ISSUE THREAD

**Issue by Kaki256** [traP-jp/stam-prolog#24]
https://q.trap.jp/messages/6eb6203b-4f28-4c68-919f-97ba024154dc

**Comment by H1rono** [comment]
https://q.trap.jp/messages/b9d1cbd5-09b4-49f3-b4be-570e532071cd

**Comment by H1rono** [comment]
```python
>>> from stam_prolog import ast
>>> from stam_prolog.evaluate.match import match_stamps
>>> d = [ast.Stamp(":hoge:"), ast.Stamp(":fuga:"), ast.Stamp(":hoge:"), ast.Stamp(":hoge:")]
>>> q = [ast.Variable(":x:"), ast.Stamp(":fuga:"), ast.Stamp(":hoge:")]
>>> match_stamps(d, q)
{Variable(name=':x:'): <FrozenList(frozen=True, [Stamp(name=':hoge:'), Stamp(name=':fuga:')])>}
```

`match_stamps_search`で失ってはいけないものを失っているかも

https://github.com/traP-jp/h23s-stam-prolog/blob/98c79f966eb6f191158ab28a76d8bd975f81937f/stam_prolog/evaluate/match.py#L8-L38

**Comment by H1rono** [comment]
> https://q.trap.jp/messages/6eb6203b-4f28-4c68-919f-97ba024154dc

動いた
https://q.trap.jp/messages/28a0af1f-818f-4acb-8884-3f4790d2c858
